### ISSUE TITLE
'withTask' isn't defined for the type

### ISSUE THREAD

**Issue by shriharip** [hpoul/flutter_async_utils#1]
hi,

The error message is: _The method 'withTask' isn't defined for the type '_MyAppState'._
Steps to reproduce:
create a new flutter project.
copy the example main dart into the main dart file of the newly created project.
This error shows up.

Thanks

**Comment by hpoul** [comment]
are you sure you added the correct version to your dependencies? `1.0.0-nullsafety.1`

**Comment by shriharip** [comment]
Herbert, I cannot add that version since it gives me this error

 Because project depends on flutter_async_utils 1.0.0-nullsafety.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because project depends on flutter_async_utils 1.0.0-nullsafety.1 which doesn't match any versions, version solving failed.)
exit code 1

**Comment by shriharip** [comment]
adding via git solved the issue

**Comment by hpoul** [comment]
looks like I forgot to publish to pub.. now it's available 😅️

**Comment by shriharip** [comment]
Yes. working fine :)
